SELECT  A.AUTHOR_ID, 
        A.AUTHOR_NAME, 
        B.CATEGORY, 
        SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (
        SELECT BOOK_ID, SALES_DATE, SALES
        FROM BOOK_SALES
        WHERE SALES_DATE LIKE '2022-01%'
    ) AS BS
    ON BS.BOOK_ID = B.BOOK_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC