WITH RECURSIVE GENS AS(
    SELECT  1 AS GENERATION,
            ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT  G.GENERATION+1,
            ED.ID
    FROM GENS G
    JOIN ECOLI_DATA ED
        ON G.ID = ED.PARENT_ID
    WHERE G.GENERATION < 3 
)

SELECT ID
FROM GENS
WHERE GENERATION = 3
ORDER BY ID