-- 자식 없는 애들 구하기

SELECT  T.PARENT_ID,
        INFO.ITEM_NAME,
        INFO.RARITY
FROM
(
    SELECT  I1.ITEM_ID AS PARENT_ID, 
            I2.ITEM_ID AS CHILD_ID
    FROM ITEM_TREE I1
    LEFT JOIN ITEM_TREE I2
        ON I1.ITEM_ID = I2.PARENT_ITEM_ID
) AS T
JOIN ITEM_INFO INFO
    ON T.PARENT_ID = INFO.ITEM_ID
WHERE T.CHILD_ID IS NULL
ORDER BY T.PARENT_ID DESC