SELECT 
    E1.ID,
    CASE
        WHEN E2.ID IS NOT NULL
        THEN COUNT(*)
        ELSE 0
    END AS CHILD_COUNT
FROM ECOLI_DATA E1
LEFT JOIN ECOLI_DATA E2
ON E1.ID = E2.PARENT_ID
GROUP BY E1.ID