# SELECT AVG(PM_VAL1) AS "PM10", AVG(PM_VAL2) AS "PM2.5"
# FROM AIR_POLLUTION
# GROUP BY YEAR(YM)
# WHERE LOCATION2="수원"
SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1),2) AS "PM10", ROUND(AVG(PM_VAL2),2) AS "PM2.5"
FROM
    (
        SELECT *
        FROM AIR_POLLUTION
        WHERE LOCATION2="수원"
    ) AS S
GROUP BY YEAR(YM)
ORDER BY YEAR(YM)