SELECT DISTINCT ON1.USER_ID, ON1.PRODUCT_ID
FROM ONLINE_SALE AS ON1
JOIN ONLINE_SALE AS ON2
ON ON1.USER_ID = ON2.USER_ID
    AND ON1.PRODUCT_ID = ON2.PRODUCT_ID
    AND ON1.ONLINE_SALE_ID != ON2.ONLINE_SALE_ID
ORDER BY ON1.USER_ID, ON1.PRODUCT_ID DESC