SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, MRI.MAX_FAVORITES AS FAVORITES
FROM REST_INFO AS RI 
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS MRI
ON RI.FOOD_TYPE=MRI.FOOD_TYPE AND RI.FAVORITES = MRI.MAX_FAVORITES
ORDER BY RI.FOOD_TYPE DESC