SELECT  UGU.USER_ID, 
        UGU.NICKNAME, 
        CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS `전체주소`, 
        CONCAT(SUBSTRING(TLNO, 1, 3),'-',
              SUBSTRING(TLNO,4 ,4), '-',
              SUBSTRING(TLNO, 8, 4)
              )AS `전화번호`
FROM USED_GOODS_BOARD AS UGB
JOIN USED_GOODS_USER AS UGU
    ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.WRITER_ID) >= 3
ORDER BY UGU.USER_ID DESC