-- 코드를 작성해주세
SELECT CONCAT(QUARTER,"Q") AS QUARTER ,COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT QUARTER(DIFFERENTIATION_DATE) AS QUARTER FROM ECOLI_DATA
    ) AS QUARTERGROUP
GROUP BY QUARTER
ORDER BY QUARTER