SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM 
    (
        SELECT HOST_ID
        FROM PLACES
        GROUP BY HOST_ID
        HAVING COUNT(*) >= 2
        ORDER BY ID
    ) AS MULTIUSER
JOIN PLACES
ON MULTIUSER.HOST_ID = PLACES.HOST_ID
ORDER BY PLACES.ID