-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
-- 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * OM5.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN
(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM
        (
            SELECT PRODUCT_ID, AMOUNT
            FROM FOOD_ORDER
            WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
        ) AS OM5_PRE
    GROUP BY PRODUCT_ID
) AS OM5
ON FP.PRODUCT_ID = OM5.PRODUCT_ID
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID


    
-- 5월달 식품들만 모은다. 같은 ID 묶는다. 정리한다.