-- 자동차 종류가 '트럭'인 자동차의 대여 기록
-- 대여 기록 별로 대여 금액
-- 대여 기록 ID와 대여 금액 리스트 출력
-- 대여 금액을 기준 내림차순 정렬, 대여 기록 ID를 기준 내림차순
WITH RENTAL_INFO AS (
    SELECT  CRCR.HISTORY_ID,
            CRCC.DAILY_FEE,
            DATEDIFF(CRCR.END_DATE, CRCR.START_DATE) + 1 AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCR
    JOIN CAR_RENTAL_COMPANY_CAR CRCC
        ON CRCR.CAR_ID = CRCC.CAR_ID
    WHERE CRCC.CAR_TYPE = '트럭'
)

SELECT  R.HISTORY_ID,
        CAST(R.DAILY_FEE * R.DIFF * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100 AS UNSIGNED) AS FEE
FROM RENTAL_INFO R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON P.CAR_TYPE = '트럭'
    AND P.DURATION_TYPE = (
        SELECT DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE R.DIFF >= CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED)
        ORDER BY CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED) DESC
        LIMIT 1
    )
ORDER BY FEE DESC, R.HISTORY_ID DESC