-- 자동차 종류가 '트럭'인 자동차의 대여 기록
-- 대여 기록 별로 대여 금액
-- 대여 기록 ID와 대여 금액 리스트 출력
-- 대여 금액을 기준 내림차순 정렬, 대여 기록 ID를 기준 내림차순
SELECT  CRCR.HISTORY_ID, 
        CAST(CRCC.DAILY_FEE * (DATEDIFF(CRCR.END_DATE, CRCR.START_DATE) + 1)
            *(100 - IFNULL(CRCD.DISCOUNT_RATE,0)) / 100 AS UNSIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCR
    ON CRCR.CAR_ID = CRCC.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCD
    ON CRCD.CAR_TYPE = CRCC.CAR_TYPE
    AND DATEDIFF(CRCR.END_DATE, CRCR.START_DATE) + 1 >= REPLACE(CRCD.DURATION_TYPE, '일 이상', '')
    AND CRCD.DURATION_TYPE = (
        SELECT DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭'
            AND DATEDIFF(CRCR.END_DATE, CRCR.START_DATE) + 1 >= REPLACE(DURATION_TYPE, '일 이상', '')
        ORDER BY CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED) DESC
        LIMIT 1
    )
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CRCR.HISTORY_ID DESC