WITH RECURSIVE NUMS AS (
    SELECT 0 AS HOUR, 0 AS COUNT                -- 시작 숫자
    UNION ALL
    SELECT HOUR + 1, 0 FROM NUMS WHERE HOUR < 23             -- 종료 조건
)

SELECT  N.HOUR, 
        COUNT(A.DATETIME) AS COUNT
FROM NUMS N
LEFT JOIN ANIMAL_OUTS A
    ON N.HOUR = HOUR(A.DATETIME)
GROUP BY N.HOUR
ORDER BY N.HOUR
