SELECT 
    T.ITEM_ID AS ITEM_ID,
    II.ITEM_NAME,
    II.RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS PARENT
    ON PARENT.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO AS II
    ON II.ITEM_ID = T.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;