SELECT R.T_ID AS ITEM_ID, II.ITEM_NAME, II.RARITY
FROM (
    SELECT T.ITEM_ID AS T_ID, T.PARENT_ITEM_ID, I.ITEM_ID AS I_ID
    FROM ITEM_INFO AS I
    JOIN ITEM_TREE AS T
        ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = "RARE"
) AS R
JOIN ITEM_INFO AS II
    ON II.ITEM_ID = R.T_ID
ORDER BY II.ITEM_ID DESC