-- 자식 정보 출력하기
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO INFO
LEFT JOIN 
(
    SELECT IT.ITEM_ID AS CHILD_ID, IT.PARENT_ITEM_ID AS PARENT_ID
    FROM ITEM_INFO II 
    JOIN ITEM_TREE IT
        ON II.ITEM_ID = IT.PARENT_ITEM_ID
    WHERE II.RARITY = 'RARE'
) AS SUB
ON INFO.ITEM_ID = SUB.CHILD_ID
WHERE SUB.PARENT_ID IS NOT NULL
ORDER BY INFO.ITEM_ID DESC