SELECT MONTH(RH.START_DATE) AS MONTH, RH.CAR_ID, COUNT(*) AS RECORDS 
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5 
) AS R5
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
ON R5.CAR_ID = RH.CAR_ID
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC