SELECT D.ID,
       MAX(D.EMAIL) AS EMAIL,
       MAX(D.FIRST_NAME) AS FIRST_NAME,
       MAX(D.LAST_NAME) AS LAST_NAME
FROM SKILLCODES AS S
JOIN DEVELOPERS AS D
  ON S.CODE & D.SKILL_CODE = S.CODE
WHERE S.NAME IN ('Python', 'C#')
GROUP BY D.ID
ORDER BY D.ID;