-- 스킬코드를 &연산을 통해서 자기자신이 나오면 해당 스킬을 가진 것으로 간주
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES AS S
JOIN DEVELOPERS AS D
ON S.CODE & D.SKILL_CODE = S.CODE
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID