SELECT  YEAR(ED1.DIFFERENTIATION_DATE) AS YEAR,
        (ED2.SIZE_MAX - ED1.SIZE_OF_COLONY) AS YEAR_DEV,
        ID
FROM ECOLI_DATA ED1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS ED2
ON YEAR(ED1.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR(ED1.DIFFERENTIATION_DATE), YEAR_DEV
