
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
     MAX_COLONY - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS ED
JOIN (
        SELECT YEAR(DIFFERENTIATION_DATE) AS MAX_YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_COLONY 
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS MS
ON YEAR(ED.DIFFERENTIATION_DATE) = MS.MAX_YEAR
ORDER BY YEAR, YEAR_DEV