SELECT  FI.ID,
        FNI.FISH_NAME,
        FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH = 
(
    SELECT MAX(LENGTH) AS LENGTH
    FROM FISH_INFO F
    WHERE FI.FISH_TYPE = F.FISH_TYPE
    GROUP BY FISH_TYPE
    
)
ORDER BY FI.ID ASC