-- 2022년도 평가 점수가 가장 높은 사원들의 점수, 사번, 성명, 직책, 이메일
-- HR_EMPLOYEES: EMP_NO, EMP_NAME, POSITION EMAIL
-- HR_GRADE: SCORE
SELECT A.SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM 
    (
        SELECT SUM(SCORE) AS SCORE, EMP_NO
        FROM HR_GRADE
        WHERE YEAR=2022
        GROUP BY EMP_NO
    ) AS A
JOIN HR_EMPLOYEES AS B 
ON A.EMP_NO=B.EMP_NO
ORDER BY SCORE DESC
LIMIT 1