SELECT CONCAT('/home/grep/src/', BGF.BOARD_ID, '/', BGF.FILE_ID, BGF.FILE_NAME, BGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD BGB
JOIN USED_GOODS_FILE BGF
    ON BGB.BOARD_ID = BGF.BOARD_ID
WHERE BGB.VIEWS =
(
    SELECT MAX(VIEWS) AS VIEWS
    FROM USED_GOODS_BOARD   
)
ORDER BY BGF.FILE_ID DESC