SELECT  B.CATEGORY,
        SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN
(
    SELECT BOOK_ID, SALES_DATE, SALES
    FROM BOOK_SALES
) AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC