SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
FROM
(
    SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE,
            RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '김치', '국', '식용유')
) AS FP
WHERE RNK = 1
ORDER BY FP.PRICE DESC