SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN 
    (
        SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY
    ) AS MFP
ON FP.PRICE = MFP.MAX_PRICE AND FP.CATEGORY = MFP.CATEGORY
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY FP.PRICE DESC