SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM (
    SELECT 
        CATEGORY, PRICE, PRODUCT_NAME,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
) AS PRODUCT_RNK
WHERE RNK = 1
ORDER BY PRICE DESC;


# SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
# FROM FOOD_PRODUCT FP
# JOIN 
#     (
#         SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
#         FROM FOOD_PRODUCT
#         GROUP BY CATEGORY
#     ) AS MFP
# ON FP.PRICE = MFP.MAX_PRICE AND FP.CATEGORY = MFP.CATEGORY
# WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY FP.PRICE DESC