SELECT COUNT(*) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, FI.FISH_TYPE
FROM 
(
    SELECT  FISH_TYPE,
            CASE
                WHEN LENGTH IS NULL
                THEN 10
                ELSE LENGTH
            END AS LENGTH
    FROM FISH_INFO
) AS FI
GROUP BY FI.FISH_TYPE
HAVING AVG(FI.LENGTH) >= 33.0
ORDER BY FI.FISH_TYPE